module.exports = function(G, R, L, S, SU, W, F, XE, gS, SP, SK, groupNames) {
  var lines = [];
  var body;

  for (var gi = 0; gi < groupNames.length; gi++) {
    var gn = groupNames[gi];
    switch (gn) {
      case 'HALT': body = 'return st.s.length?st.s[st.s.length-1]:undefined;'; break;
      case 'PUSH_CONST': body = 'st.s.push(' + G + '(' + R + '(st)));'; break;
      case 'PUSH_VAR': body = 'st.s.push(' + L + '(st,' + G + '(' + R + '(st))));'; break;
      case 'STORE_VAR': body = SU + '(st,' + G + '(' + R + '(st)),st.s[st.s.length-1]);'; break;
      case 'DECLARE_VAR': body = '{var _dn=' + G + '(' + R + '(st));var _dv=st.s.pop();if(typeof __PF__!=="undefined"&&__PF__.hasOwnProperty(_dn))_dv=__PF__[_dn];st.c.set(_dn,_dv);}'; break;
      case 'POP': body = 'st.s.pop();'; break;
      case 'DUP': body = 'st.s.push(st.s[st.s.length-1]);'; break;
      case 'ADD': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l+r);}'; break;
      case 'SUB': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l-r);}'; break;
      case 'MUL': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l*r);}'; break;
      case 'DIV': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l/r);}'; break;
      case 'MOD': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l%r);}'; break;
      case 'EXP': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(Math.pow(l,r));}'; break;
      case 'EQ': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l==r);}'; break;
      case 'NEQ': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l!=r);}'; break;
      case 'STRICT_EQ': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l===r);}'; break;
      case 'STRICT_NEQ': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l!==r);}'; break;
      case 'LT': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l<r);}'; break;
      case 'LTE': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l<=r);}'; break;
      case 'GT': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l>r);}'; break;
      case 'GTE': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l>=r);}'; break;
      case 'AND': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l&&r);}'; break;
      case 'OR': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l||r);}'; break;
      case 'NOT': body = 'st.s.push(!st.s.pop());'; break;
      case 'NULLISH': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l!=null?l:r);}'; break;
      case 'BIT_AND': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l&r);}'; break;
      case 'BIT_OR': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l|r);}'; break;
      case 'BIT_XOR': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l^r);}'; break;
      case 'BIT_NOT': body = 'st.s.push(~st.s.pop());'; break;
      case 'LSHIFT': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l<<r);}'; break;
      case 'RSHIFT': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l>>r);}'; break;
      case 'URSHIFT': body = '{var r=st.s.pop();var l=st.s.pop();st.s.push(l>>>r);}'; break;
      case 'JMP': body = 'st.i=' + R + '(st);'; break;
      case 'JMP_IF_FALSE': body = 'if(!st.s.pop())st.i=' + R + '(st);else st.i+=4;'; break;
      case 'JMP_IF_TRUE': body = 'if(st.s.pop())st.i=' + R + '(st);else st.i+=4;'; break;
      case 'CALL': body = '{var ac=' + R + '(st),a=[];for(var i=0;i<ac;i++)a.unshift(st.s.pop());var f=st.s.pop();if(f&&f._v){var __fd__=f._o||f;var __rp__=' + F + '(__fd__,a,f._s||st.c,f._ct,undefined);st.s.push(__fd__.async?__rp__:await __rp__);}else if(typeof f==="function"){st.s.push(f.apply(st.t,a));}else{throw new TypeError("Cannot call "+typeof f);}}'; break;
      case 'CALL_METHOD': body = '{var ac=' + R + '(st),mn=' + G + '(' + R + '(st)),a=[];for(var i=0;i<ac;i++)a.unshift(st.s.pop());var o=st.s.pop();if(o===null||o===undefined){st.s.push(undefined);}else{var m=o[mn];if(m&&m._v){var __fd2__=m._o||m;var __rp2__=' + F + '(__fd2__,a,m._s||st.c,m._ct,o);st.s.push(__fd2__.async?__rp2__:await __rp2__);}else if(typeof m==="function"){st.s.push(m.apply(o,a));}else{st.s.push(undefined);}}}'; break;
      case 'NEW': body = '{var ac=' + R + '(st),a=[];for(var i=0;i<ac;i++)a.unshift(st.s.pop());var ctor=st.s.pop();if(ctor&&ctor._v){var inst=Object.create(ctor.prototype);var r=ctor.apply(inst,a);if(r&&typeof r.then==="function")await r;if(r&&typeof r==="object"&&r!==inst)st.s.push(r);else st.s.push(inst);}else if(typeof ctor==="function"){try{var inst=Reflect.construct(ctor,a);st.s.push(inst);}catch(e){var inst=Object.create(ctor.prototype);var r=ctor.apply(inst,a);st.s.push(r&&typeof r==="object"?r:inst);}}else{st.s.push({});}}'; break;
      case 'RETURN': body = '{var rv=st.s.length?st.s.pop():undefined;if(st.y.length>0){var ti=st.y[st.y.length-1];if(ti.finallyAddr>=0){st.y.pop();st._retv=rv;st.i=ti.finallyAddr;break;}}while(st.l.length>0){var fr=st.l.pop();st.c=fr.c;st.t=fr.t;}return rv;}'; break;
      case 'TYPEOF': body = '{var v=st.s.pop();st.s.push(v&&v._v?"function":typeof v);}'; break;
      case 'INSTANCEOF': body = '{var c=st.s.pop(),o=st.s.pop();if(c&&c._v){var _proto=c.prototype;if(_proto){var _check=o;while(_check){if(_check===_proto){st.s.push(true);break;}_check=Object.getPrototypeOf(_check);}if(!_check)st.s.push(false);}}else if(typeof c==="function"){st.s.push(o instanceof c);}else{st.s.push(false);}}'; break;
      case 'IN': body = '{var o=st.s.pop(),p=st.s.pop();st.s.push(p in o);}'; break;
      case 'DELETE': body = '{var p=st.s.pop(),o=st.s.pop();st.s.push(o!=null?delete o[p]:true);}'; break;
      case 'GET_PROP': body = '{var pn=' + G + '(' + R + '(st)),o=st.s.pop();st.s.push(o!=null?o[pn]:undefined);}'; break;
      case 'SET_PROP': body = '{var pn=' + G + '(' + R + '(st)),v=st.s.pop(),o=st.s.pop();if(o!=null)o[pn]=v;st.s.push(v);}'; break;
      case 'GET_INDEX': body = '{var idx=st.s.pop(),o=st.s.pop();st.s.push(o!=null?o[idx]:undefined);}'; break;
      case 'SET_INDEX': body = '{var v=st.s.pop(),idx=st.s.pop(),o=st.s.pop();if(o!=null)o[idx]=v;st.s.push(v);}'; break;
      case 'NEW_OBJ': body = 'st.s.push({});'; break;
      case 'NEW_ARR': body = '{var len=' + R + '(st),a=[];for(var i=0;i<len;i++)a.unshift(st.s.pop());st.s.push(a);}'; break;
      case 'PUSH_FUNC': body = '{var fd=' + G + '(' + R + '(st)),vf=' + W + '(fd,st);st.s.push(vf);}'; break;
      case 'OPTIONAL_CHAIN': body = '{var _ocpn=' + G + '(' + R + '(st));if(st.s[st.s.length-1]==null){st.s.pop();st.s.push(undefined);}else{var _oco=st.s.pop();st.s.push(_oco!=null?_oco[_ocpn]:undefined);}}'; break;
      case 'ENTER_SCOPE': body = '{st.l.push({i:st.i,c:st.c,t:st.t,s:st.s.slice()});var ns=new Map();ns.__p=st.c;st.c=ns;}'; break;
      case 'EXIT_SCOPE': body = '{if(st.l.length>0){var fr=st.l.pop();st.c=fr.c;st.t=fr.t;}}'; break;
      case 'TRY': body = '{var inf=' + G + '(' + R + '(st));st.y.push({catchAddr:inf.catchAddr,finallyAddr:inf.finallyAddr});}'; break;
      case 'THROW': body = '{var err=st.s.pop();if(st.y.length===0)throw err;var ti=st.y[st.y.length-1];if(ti.catchAddr>=0){st.y.pop();st.s.push(err);st.i=ti.catchAddr;}else if(ti.finallyAddr>=0){st._throwing=true;st.s.push(err);st.i=ti.finallyAddr;}else{st.y.pop();throw err;}}'; break;
      case 'CATCH': body = '{}'; break;
      case 'FINALLY': body = '{}'; break;
      case 'END_TRY': body = '{if(st.y.length>0){var _tr=st.y.pop();if(st._throwing){st._throwing=false;var _err=st.s.pop();throw _err;}}if(st._retv!==undefined){var _rv=st._retv;st._retv=undefined;while(st.l.length>0){var fr=st.l.pop();st.c=fr.c;st.t=fr.t;}return _rv;}}'; break;
      case 'INC_PRE': body = '{var n=' + G + '(' + R + '(st)),cur=' + L + '(st,n)||0;' + SU + '(st,n,cur+1);st.s.push(cur+1);}'; break;
      case 'INC_POST': body = '{var n=' + G + '(' + R + '(st)),cur=' + L + '(st,n)||0;st.s.push(cur);' + SU + '(st,n,cur+1);}'; break;
      case 'DEC_PRE': body = '{var n=' + G + '(' + R + '(st)),cur=' + L + '(st,n)||0;' + SU + '(st,n,cur-1);st.s.push(cur-1);}'; break;
      case 'DEC_POST': body = '{var n=' + G + '(' + R + '(st)),cur=' + L + '(st,n)||0;st.s.push(cur);' + SU + '(st,n,cur-1);}'; break;
      case 'NEG': body = 'st.s.push(-st.s.pop());'; break;
      case 'POS': body = 'st.s.push(+st.s.pop());'; break;
      case 'SET_PROP_OBJ': body = '{var pn=' + G + '(' + R + '(st)),v=st.s.pop(),o=st.s[st.s.length-1];if(o!=null)o[pn]=v;}'; break;
      case 'SET_PROP_OBJ_COMPUTED': body = '{var k=st.s.pop(),v=st.s.pop(),o=st.s[st.s.length-1];if(o!=null)o[k]=v;}'; break;
      case 'TERNARY': body = '{var alt=st.s.pop(),cons=st.s.pop(),tst=st.s.pop();st.s.push(tst?cons:alt);}'; break;
      case 'THIS': body = 'st.s.push(st.t);'; break;
      case 'SUPER': body = 'st.s.push(st.t);'; break;
      case 'REST_ARGS': body = '{var a=st.s.pop();if(Array.isArray(a)){for(var i=0;i<a.length;i++)st.s.push(a[i]);}else if(a&&typeof a[Symbol.iterator]==="function"){var it=a[Symbol.iterator]();var nx;while(!(nx=it.next()).done)st.s.push(nx.value);}}'; break;
      case 'ARRAY_PUSH': body = '{var _av=st.s.pop();var _aa=st.s[st.s.length-1];if(Array.isArray(_aa))_aa.push(_av);}'; break;
      case 'ARRAY_SPREAD': body = '{var _sp=st.s.pop();var _arr=st.s[st.s.length-1];if(_sp&&typeof _sp[Symbol.iterator]==="function"){var _it=_sp[Symbol.iterator]();var _nx;while(!(_nx=_it.next()).done)_arr.push(_nx.value);}else if(Array.isArray(_sp)){for(var _si=0;_si<_sp.length;_si++)_arr.push(_sp[_si]);}}'; break;
      case 'OBJ_SPREAD': body = '{var src=st.s.pop(),dst=st.s[st.s.length-1];if(src&&typeof src==="object"){for(var k in src){if(Object.prototype.hasOwnProperty.call(src,k))dst[k]=src[k];}}}'; break;
      case 'FOR_OF_ITER': body = '{var itb=st.s.pop(),it=itb&&itb[Symbol.iterator]?itb[Symbol.iterator]():null;st.s.push(it||{next:function(){return{done:true};}});}'; break;
      case 'FOR_IN_ITER': body = '{var o=st.s.pop(),ks=[];if(o!=null){for(var k in o)ks.push(k);}st.s.push(ks);}'; break;
      case 'AWAIT': body = '{var p=st.s.pop();if(p&&typeof p.then==="function"){st.s.push(await p);}else{st.s.push(p);}}'; break;
      case 'YIELD': body = 'st.s.push(st.s.pop());'; break;
      case 'CLASS_BODY': body = '{var sc=st.s.pop(),cls=st.s[st.s.length-1];if(sc&&cls&&typeof sc==="function"){var pr=Object.create(sc.prototype);pr.constructor=cls;cls.prototype=pr;cls.__s=sc;}}'; break;
      case 'SUPER_CALL': body = '{var ac=' + R + '(st),a=[];for(var i=0;i<ac;i++)a.unshift(st.s.pop());var sC=st.s.pop();if(sC&&sC._v){var __sc_fd__=sC._o||sC;var __sc_r__=' + F + '(__sc_fd__,a,sC._s||st.c,undefined,st.t);if(__sc_fd__.async)await __sc_r__;st.s.push(st.t);}else if(typeof sC==="function"){var r=sC.apply(st.t,a);if(r&&typeof r.then==="function"){st.s.push(await r);}else{st.s.push(r);}}else{st.s.push(st.t);}}'; break;
      case 'SUPER_METHOD': body = '{var ac=' + R + '(st),mn=' + G + '(' + R + '(st)),a=[];for(var i=0;i<ac;i++)a.unshift(st.s.pop());var sl=st.s.pop();var sp=sl&&sl.constructor&&sl.constructor.__s&&sl.constructor.__s.prototype;if(sp){var _d=Object.getOwnPropertyDescriptor(sp,mn);if(_d&&typeof _d.get==="function"){st.s.push(_d.get.call(sl));}else{var m=sp[mn];if(typeof m==="function"){var r=m.apply(sl,a);if(r&&typeof r.then==="function"){st.s.push(await r);}else{st.s.push(r);}}else{st.s.push(undefined);}}}else{st.s.push(undefined);}}'; break;
      case 'IMPORT': body = '{}'; break;
      case 'EXPORT': body = '{}'; break;
      case 'DEAD_CODE': body = R + '(st);'; break;
      case 'ANTI_DEBUG': body = '{var start=Date.now(),j=0;for(var i=0;i<500000;i++)j+=i&1;if(Date.now()-start>50){__B__=new Uint8Array(0);__DC__=[];throw new Error("Anti-debug");}}'; break;
      case 'DEBUG_BREAK': body = 'if(__D__)debugger;'; break;
      case 'SEGMENT_SWITCH': body = '{var segId=__B__[st.i++]%__NUM_SEG__;if(segId!==__OT_CUR__&&segId<__NUM_SEG__){__OT_CUR__=segId;__OT__=__OT_ALL__[segId];}}'; break;
      case 'FAKE_ADD': body = '{var fv=' + R + '(st);st.fakeStack.push(fv);}'; break;
      case 'FAKE_CALL': body = '{' + R + '(st);st.fakeStack.push(Math.random());}'; break;
      case 'DESTRUCTURE_ARR': body = '{var _dc=' + R + '(st);var _arr=st.s.pop();for(var _di=_dc-1;_di>=0;_di--){var _dn=' + SK + '(st);var _dv=_arr!=null?_arr[_di]:undefined;st.c.set(_dn,_dv);}}'; break;
      case 'DESTRUCTURE_OBJ': body = '{var _dc=' + R + '(st);var _obj=st.s.pop();for(var _di=_dc-1;_di>=0;_di--){var _kn=' + SK + '(st);var _dn=' + SK + '(st);var _dv=_obj!=null?_obj[_kn]:undefined;st.c.set(_dn,_dv);}}'; break;
      case 'RETURN_TRAMP': body = '{var rv=st.s.length?st.s.pop():undefined;if(st.y.length>0){var ti=st.y[st.y.length-1];if(ti.finallyAddr>=0){st._retv=rv;st.i=ti.finallyAddr;break;}}while(st.l.length>0){var fl=st.l.pop();st.c=fl.c;st.t=fl.t;}if(st._trampStack&&st._trampStack.length>0){var fr=st._trampStack.pop();st.c=fr.c;st.t=fr.t;st.i=fr.i;st.s.push(rv);}else{return rv;}}'; break;
      case 'CALL_TRAMP': body = '{var ac=' + R + '(st),a=[];for(var i=0;i<ac;i++)a.unshift(st.s.pop());var f=st.s.pop();if(f&&f._v){var __fd__=f._o||f;var params=__fd__.params||[];var ns=new Map();ns.__p=f._s||st.c;st._trampStack.push({c:st.c,t:st.t,i:st.i});for(var j=0;j<params.length;j++){var pn=params[j];if(pn.charAt(0)==="."&&pn.charAt(1)==="."&&pn.charAt(2)==="."){var rest=[];for(var k=j;k<a.length;k++)rest.push(a[k]);ns.set(pn.slice(3),rest);break;}else{ns.set(pn,j<a.length?a[j]:undefined);}}if(!__fd__.isArrow)ns.set("arguments",a);st.c=ns;st.t=__fd__._this!==undefined?__fd__._this:(__fd__.isArrow?(f._ct||st.t):st.t);st.i=__fd__.addr;}else if(typeof f==="function"){st.s.push(f.apply(st.t,a));}else{throw new TypeError("Cannot call "+typeof f);}}'; break;
      case 'CALL_METHOD_TRAMP': body = '{var ac=' + R + '(st),mn=' + G + '(' + R + '(st)),a=[];for(var i=0;i<ac;i++)a.unshift(st.s.pop());var o=st.s.pop();if(o===null||o===undefined){st.s.push(undefined);}else{var m=o[mn];if(m&&m._v){var __fd__=m._o||m;var params=__fd__.params||[];var ns=new Map();ns.__p=m._s||st.c;st._trampStack.push({c:st.c,t:st.t,i:st.i});for(var j=0;j<params.length;j++){var pn=params[j];if(pn.charAt(0)==="."&&pn.charAt(1)==="."&&pn.charAt(2)==="."){var rest=[];for(var k=j;k<a.length;k++)rest.push(a[k]);ns.set(pn.slice(3),rest);break;}else{ns.set(pn,j<a.length?a[j]:undefined);}}if(!__fd__.isArrow)ns.set("arguments",a);st.c=ns;st.t=__fd__._this!==undefined?__fd__._this:(__fd__.isArrow?(m._ct||st.t):o);st.i=__fd__.addr;}else if(typeof m==="function"){st.s.push(m.apply(o,a));}else{st.s.push(undefined);}}}'; break;
      case 'GET_PRIVATE': body = '{var pn=' + G + '(' + R + '(st)),o=st.s.pop();var priv=__PRIVATE_MAP__.get(o);st.s.push(priv?priv[pn]:undefined);}'; break;
      case 'SET_PRIVATE': body = '{var pn=' + G + '(' + R + '(st)),v=st.s.pop(),o=st.s.pop();var priv=__PRIVATE_MAP__.get(o);if(!priv){priv={};__PRIVATE_MAP__.set(o,priv);}priv[pn]=v;st.s.push(v);}'; break;
      default: body = '{}'; break;
    }
    lines.push('        case ' + gi + ':' + body + ' break;');
  }
  var asyncBody = lines.join('\n');
  var syncBody = asyncBody.replace(/await /g, '');
  return {async: asyncBody, sync: syncBody};
};